### ISSUE TITLE
Constant errors flooding log and my network

### ISSUE THREAD

**Issue by kbrown01** [humbertogontijo/homeassistant-roborock#163] opened 2023-01-24 22:17 UTC
2023-01-24 14:12:39.031 ERROR (MainThread) [custom_components.roborock.api.api] Roborock mqtt client disconnected (rc: 7)
2023-01-24 14:13:53.660 ERROR (MainThread) [custom_components.roborock] Error fetching roborock data: Timeout after 4 waiting for response

392,000 per day

**Comment by inertia666** [comment] 2023-01-26 11:46
This is happening to me as well. Funnily enough, my app stopped working on my home network and cannot connect unless I am using the mobile network. I think my home API is blacklisted and I am concerned that this integration has caused it.

I have emailed Roborock about the app problem but for now I need to uninstall this.

**Comment by Specialmias** [comment] 2023-01-27 02:20
I've also been blacklisted by roborock. I can confirm with my backup internet connection. My regular IP is kaput.

**Comment by inertia666** [comment] 2023-01-29 14:14
I wrote the to CS and they replied "wait for 2 days and if not try adding the Roborock to the Mi Home app". Although, the second bit of advice was no solution I wanted to go with it does appear that my ip blacklist has been removed, presumably, automatically.

**Comment by bhchew** [comment] 2023-01-30 02:10
Reporting the same, was disconnected from the app after using the integration. Tried to pair my bot with robo app againand hit connection error

**Comment by inertia666** [comment] 2023-01-31 10:37
Now I have gotten back into the app and reinstalled the integration everything seems ok again. For now, at least.

**Comment by ksheumaker** [comment] 2023-02-01 03:02
Same thing happened to me. Robot was stuck under the couch for a two days (before I took the time to rescue it), and likely powered down during that time. HA integration was still running.

When I put it back on the dock didn't work. Checked the app and it was acting very slow and weird.  Removed app, reset robot wifi and could never get it to connect to roborock to add to my account.

Switched to my backup internet connection with different IP and now works fine now. 

So I think roborock is blocking IPs for some reason.  I don't know if it does a lot of queries to their servers when the device is offline?

I will try in a few days to switch Internet back and see if it starts working again.

**Comment by humbertogontijo** [comment] 2023-02-01 11:23
@ksheumaker were you using the latest version? It was indeed retrying to connect indefinitely when robot was offline, in older versions, but latest version I made some changes to avoid it

**Comment by 0xGiddi** [comment] 2023-02-02 16:09
I had the same issue. Roborock blacklisted my IP address. I have solved it by resetting the robots Wi-Fi and reregistering it with a new account created in a different region ( after two weeks of using the mi home app)

The robot was not offline while this happened , but the HA integration would go offline after a while, usually a  python index error (did not have time to debug it back then)

This happened about two weeks ago on the latest version then, since then I disabled the integration but the app still did not work  

@humbertogontijo you might want to add a warning at the top of the README that this may cause Roborock servers to blacklist users IP address and is still under testing. 

I wonder if this is due to excessive polling of the robot servers in some edge cases. Maybe a global rate limit?

**Comment by 0xGiddi** [comment] 2023-02-02 16:33
> 56 disconnections against 1600+ that was happening in a couple of day interval.
> 
> There is no way to have 0 disconnections, this is just how Roborock's mqtt work

Agreed. I don’t expect 0,  but  had “a few” more disconnections :) 

I really hope the latest version solves it as it is an amazing project. I wonder if creating a second account in a different region and sharing the device with it will be some sort of failsafe as it will block the IP only in the region servers of the second account. The integration definitely sees the shared devices as I saw one that was shared with me. It does mean though that if the integration gets remote viewing capabilities it will not work with the shared account. 

I’ll have to test it when I get a chance and report back (if it bans me again)


My log for reference: 

```
This error originated from a custom integration.

Logger: custom_components.roborock.api.api
Source: custom_components/roborock/api/api.py:173 
Integration: Roborock (documentation, issues) 
First occurred: January 17, 2023 at 17:14:31 (3562501 occurrences) 
Last logged: 11:38:06

Roborock mqtt client disconnected (rc: 7)
Roborock mqtt client disconnected (rc: 2)
```

**Comment by humbertogontijo** [comment] 2023-02-02 16:58
Wow! 3562501 occurrences!? I'd recommend you to update the integration. Otherwise you will get banned again quickly

**Comment by ronaldt80** [comment] 2023-02-11 16:15
hi, great work, very interested in using this - @0xGiddi did sharing the device with a second account work and prevent bans of the main account?

**Comment by 0xGiddi** [comment] 2023-02-11 16:20
@ronaldt80 
 So far I have not seen any problems regarding bans. However this also might be changes made in the versions after I got banned.

**Comment by WilliamHusum** [comment] 2023-02-14 11:21
I'm still seeing this problem, I think. The integration has failed and I'm getting these errors in the logs: 
```
This error originated from a custom integration.

Logger: custom_components.roborock.api.api
Source: custom_components/roborock/api/api.py:225
Integration: Roborock (documentation, issues)
First occurred: 09:24:32 (94 occurrences)
Last logged: 11:32:34

Roborock mqtt client disconnected (rc: 7)
Roborock mqtt client disconnected (rc: 16)
```


```
This error originated from a custom integration.

Logger: custom_components.roborock
Source: helpers/update_coordinator.py:215
Integration: Roborock (documentation, issues)
First occurred: 09:23:58 (93 occurrences)
Last logged: 11:31:39

Error fetching roborock data: Timeout after 4 seconds waiting for response
```

**Comment by lukaskuerzdoerfer** [comment] 2023-02-25 08:25
Are there any updates about this issue?
Do i get an ban if i setup this integration or is this now fixed?

**Comment by WilliamHusum** [comment] 2023-02-25 09:12
> Are there any updates about this issue? Do i get an ban if i setup this integration or is this now fixed?

I reconnected the roborock in the app and reinstalled it in Home Assistant and haven't had any problems since, so it seems to be fixed.

**Comment by Inrego** [comment] 2023-03-07 06:50
I installed this a while ago, but hesitant to put it in use yet due to this issue.

So far looks to be resolved it seems. Any updates from people using it?

**Comment by ronaldt80** [comment] 2023-03-07 06:51
Works like a charm

**Comment by WilliamHusum** [comment] 2023-03-07 06:52
Works great now

**Comment by jLynx** [comment] 2023-03-07 08:21
I haven't had any issues (keep in mind my roborock card is on another tab. Not sure if that means it's not constantly fetching the layout image or not. But just an FYI

**Comment by andras-tim** [comment] 2023-03-07 09:20
It works. Thank you. :slightly_smiling_face: 

But let me take a note:
If this integration is installed the official mobile app slows down. (e.g. a map load takes 10 seconds).
I think this query is still too often because everything starts working again after I disable the integration temporarily (for half a day).

**Comment by lukaskuerzdoerfer** [comment] 2023-03-07 09:26
My two Roborocks now running since 2 weeks, without any Problems. The Roborock-App seems to slow down a little bit. Maybe in a Update there will be the map only update every Hour or every 15 second when the vaccum is currently cleaning. So there should not be that mich traffic to update the map.

But: It is a really nice Integration. Keep going. 💪

**Comment by jLynx** [comment] 2023-03-07 09:28
A solution to that @andras-tim and @lukaskuerzdoerfer could be to create a 2nd account and share the robot with it. Then use that 2nd account just for HomeAssistant. That way your first/original account should not slow down. As other members in my household don't have a slow app, just mine which is used in HomeAssistant

**Comment by andras-tim** [comment] 2023-03-07 09:48
Absolutely! This is an awesome integration! Thank you! :muscle:

Thank you @jLynx for the nice workaround. It works like a charm. :smile:

**Comment by csuich2** [comment] 2023-03-07 22:54
Interesting workaround. I gave it a try but after creating a second account, logging in on the app to confirm the account is setup and then attempting to share my vacuum with the new account I keep getting an "Account does not exist" error.

I'm wondering if it is because I used a <my-email>+roborock@gmail.com style email. Has anyone else hit this issue trying to share the device?

**Comment by andras-tim** [comment] 2023-03-08 01:54
> Interesting workaround. I gave it a try but after creating a second account, logging in on the app to confirm the account is setup and then attempting to share my vacuum with the new account I keep getting an "Account does not exist" error.
> 
> I'm wondering if it is because I used a (my-email)[+roborock@gmail.com](mailto:+roborock@gmail.com) style email for the second account. Has anyone else hit this issue trying to share the device?

I tried this as well, but unfortunately, the `+` sign fails the process, therefore you can't use [Gmail alias address](https://support.google.com/mail/answer/22370?hl=en#zippy=%2Cfilter-using-your-gmail-alias) here.

**But, you have 2 options:**
1. Create a new email address
2. Add/remove one or more `.` to/from your email address ([the dots doesn't matter](https://support.google.com/mail/answer/7436150)). E.g. these are the same in Gmail:
    * `foobar@gmail.com`
    * `foo.bar@gmail.com`
    * `f.o.o.b.a.r@gmail.com`

**Comment by rocket-pants** [comment] 2023-03-13 06:59
I've also had problems connecting after updating the integration to v0.1.2. At first I was getting the mqtt error message shown above, but then created a new account with a new email, shared the vacuum, used the password authentication to log in and am now getting a different error message. The same occurs with the verification code

```
Logger: custom_components.roborock
Source: helpers/update_coordinator.py:215
Integration: Roborock ([documentation](https://github.com/humbertogontijo/homeassistant-roborock), [issues](https://github.com/humbertogontijo/homeassistant-roborock/issues))
First occurred: 14:35:25 (19 occurrences)
Last logged: 14:48:36

Error fetching roborock data: No device props found
Error fetching roborock data: Timeout after 4 seconds waiting for response
```
I'm also getting another error message

```
Logger: homeassistant.config_entries
Source: config_entries.py:1244
First occurred: 14:55:08 (1 occurrences)
Last logged: 14:55:08

Config entry 'emailaddress' for roborock integration not ready yet: None; Retrying in background
```

**Comment by Inrego** [comment] 2023-03-13 07:01
I think that's a different issue, and should have its own thread

**Comment by rocket-pants** [comment] 2023-03-13 07:26
> I think that's a different issue, and should have its own thread
May be the case - but I'm also getting the mqtt disconnected error - although it may be more of an mqtt never connected problem...

**Closed** 2023-04-04 01:49 UTC
