### ISSUE TITLE
State attributes exceed maximum size of 16384 bytes

### ISSUE THREAD

**Issue by hvorragend** [humbertogontijo/homeassistant-roborock#196] opened 2023-03-03 06:18 UTC
Is this bug already known?

```
Logger: homeassistant.components.recorder.db_schema
Source: components/recorder/db_schema.py:491 
Integration: Recorder (documentation, issues) 
First occurred: 07:15:43 (1 occurrences) 
Last logged: 07:15:43

State attributes for camera.roborock_s7 exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
```

The amount of attributes for this entity is really huge.

**Comment by Lash-L** [comment] 2023-03-03 21:01
> Is this bug already known?
> 
> 
> 
> ```
> 
> Logger: homeassistant.components.recorder.db_schema
> 
> Source: components/recorder/db_schema.py:491 
> 
> Integration: Recorder (documentation, issues) 
> 
> First occurred: 07:15:43 (1 occurrences) 
> 
> Last logged: 07:15:43
> 
> 
> 
> State attributes for camera.roborock_s7 exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
> 
> ```
> 
> 
> 
> The amount of attributes for this entity is really huge. 

This is due to the new database optimizations.

Looking at the code, the attributes it is not inputting into the database, shouldn't be inputted in the database anyways. Walls, paths, obstacles, carpet map, etc. it makes sense it would be large. 


I'm currently working on converting this into a core integration, the map/ camera are not in the initial release, but once I get to that point I will find a way to make sure that these attributes don't attempt to get added to the database. Then I will add it here as well

**Comment by Menelao147** [comment] 2023-03-19 18:26
While the problem is solved, you can exclude the sensor from [recorder](https://www.home-assistant.io/integrations/recorder/) and [history](https://www.home-assistant.io/integrations/history/).

**Comment by Lash-L** [comment] 2023-03-21 01:06
@humbertogontijo Taking another look at this - are the extra_state_attributes even used? Do one of the exterior map cards use it? Or potentially something I am missing? 

I removed the extra_state_attributes in my dev instance and it had no affect on the map displaying. I don't have HACS on my dev environment though, so I can't check the extra lovelace card or anything. Was curious if you knew off the top of your head?

**Comment by humbertogontijo** [comment] 2023-03-21 01:08
@Lash-L Yes, the extra attributes are used in the Lovelace Xiaomi Vacuum Map card

**Comment by Lash-L** [comment] 2023-04-11 01:56
This will be included in the next major release - so I am closing this for now

**Closed by Lash-L** 2023-04-11 01:56 UTC
Labels: bug
