### ISSUE TITLE
Logger: roborock.api Source: runner.py:179 First occurred: 03:43:47 (2 occurrences) Last logged: 09:44:25  Roborock mqtt client disconnected (rc: 16)

### ISSUE THREAD

**Issue by nikrays** [humbertogontijo/homeassistant-roborock#224] opened 2023-04-05 08:12 UTC
Logger: roborock.api
Source: runner.py:179
First occurred: 03:43:47 (2 occurrences)
Last logged: 09:44:25

Roborock mqtt client disconnected (rc: 16)

**Comment by Lash-L** [comment] 2023-04-05 11:13
Are you having other issues or just this log?

**Comment by nikrays** [comment] 2023-04-06 06:37
> Are you having other issues or just this log?

Only this one

**Comment by Lash-L** [comment] 2023-04-11 01:58
The mqtt client will just disconnect and reconnect sometimes. It's not a bug or anything you need to worry about unless if it is happening extremely frequently. Closing for now

**Closed by Lash-L** 2023-04-11 01:58 UTC
