### ISSUE TITLE
Integration goes unavailable every 5 - 10 minutes

### ISSUE THREAD

**Issue by tobiasbrage** [humbertogontijo/homeassistant-roborock#251] opened 2023-04-23 07:21 UTC
I've noticed that the vacuum/integration or connection to Roborock servers goes to the state "unavailable" every 5 to 10 minutes or so.
I'm using the main branch.
![Udklip](https://user-images.githubusercontent.com/78112590/233825801-55e56f8b-0dcc-4ce1-a6b0-ea2ce2e0e99f.JPG)

**Comment by Lash-L** [comment] 2023-04-23 10:07
Do you have any logs? 

Are you on the most recent version of main?

**Comment by tobiasbrage** [comment] 2023-04-23 10:17
@Lash-L I'm on the latest version of main.
Apparently there's a timeout issue happening once in a while, see the attatched images from the log.
![Udklip](https://user-images.githubusercontent.com/78112590/233833951-96ed0904-38fd-4ea0-b202-cb6c4da676a2.JPG)
![Udklip2](https://user-images.githubusercontent.com/78112590/233833952-9b7cb9fc-d705-4971-a004-be4e376a4eab.JPG)

**Comment by dennisbekker** [comment] 2023-04-23 11:50
i have the same issue, if you need some log let me know

**Comment by Lash-L** [comment] 2023-04-23 12:22
You are using the online not the offline/local version right?

**Comment by tobiasbrage** [comment] 2023-04-23 12:45
@Lash-L correct, i'm using the online version. I haven't messed with the local integration.

**Comment by luca-angemi** [comment] 2023-04-25 11:15
Same issue, here some logs

```
2023-04-25 13:12:05.865 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/roborock/__init__.py", line 186, in async_reload_entry
    await async_setup_entry(hass, entry)
  File "/config/custom_components/roborock/__init__.py", line 124, in async_setup_entry
    await local_coordinator.async_config_entry_first_refresh()
  File "/config/custom_components/roborock/coordinator.py", line 80, in async_config_entry_first_refresh
    await asyncio.gather(*([
  File "/config/custom_components/roborock/coordinator.py", line 57, in fill_room_mapping
    room_mapping = await self.api.get_room_mapping(device_info.device.duid)
  File "/usr/local/lib/python3.10/site-packages/roborock/api.py", line 324, in get_room_mapping
    mapping = await self.send_command(device_id, RoborockCommand.GET_ROOM_MAPPING)
  File "/usr/local/lib/python3.10/site-packages/roborock/local_api.py", line 66, in send_command
    raise response
  File "/usr/local/lib/python3.10/site-packages/roborock/local_api.py", line 74, in async_local_response
    (response, err) = await self._async_response(request_id, response_protocol)
  File "/usr/local/lib/python3.10/site-packages/roborock/api.py", line 144, in _async_response
    raise RoborockTimeout(f"Timeout after {QUEUE_TIMEOUT} seconds waiting for response") from None
roborock.exceptions.RoborockTimeout: Timeout after 4 seconds waiting for response
2023-04-25 13:12:18.642 ERROR (MainThread) [roborock.api] Timeout after 4 seconds waiting for response
2023-04-25 13:14:07.619 ERROR (MainThread) [custom_components.roborock.coordinator] Unexpected error fetching roborock data: 'Field' object has no attribute 'status'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/roborock/coordinator.py", line 93, in _async_update_data
    await asyncio.gather(*[
  File "/config/custom_components/roborock/coordinator.py", line 75, in fill_device_prop
    setattr(f, f.name, getattr(device_prop, f.name))
AttributeError: 'Field' object has no attribute 'status'

```

**Comment by dennisbekker** [comment] 2023-04-25 11:28
Just for the extra information, my log is exactly the same as luca-angemi

**Comment by luca-angemi** [comment] 2023-04-25 11:43
If it can help some of the sensors keep on unknown while others arw unavailable and they never come back (same applies to the vacuum entity).
![Screenshot_20230425_134101_Home Assistant](https://user-images.githubusercontent.com/9977955/234266210-6584131a-d0cb-42a1-ad6f-cb53bf310b49.jpg)

**Comment by humbertogontijo** [comment] 2023-04-25 14:12
main branch should work now

**Comment by tobiasbrage** [comment] 2023-04-26 09:41
Redownloading the main branch and restarting seemed to have solved the issue now. Thanks for acting quickly.

**Comment by dennisbekker** [comment] 2023-04-26 10:06
Can confirm that after downloading the main branch again, restart HA, the issue is resolved.

**Comment by Lash-L** [comment] 2023-08-06 15:13
I believe everyone else in this issue had their problems resolved, but what about you @luca-angemi - has it gotten better?

**Comment by luca-angemi** [comment] 2023-08-06 16:08
I switched to the official integration a couple of releases ago so I can't tell.

**Comment by Lash-L** [comment] 2023-08-06 16:10
Will close this issue for now then

**Closed by Lash-L** 2023-08-06 16:10 UTC
